project:
  type: website
  output-dir: docs

website:
  title: "Peiyi.H"
  navbar:
    background: "#508C9B"
    right:
      - href: dataViz.qmd
        text: DataViz
      - href: gallery.qmd
        text: Gallery
  favicon: images/favicon.ico

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Noto Sans TC"
    
editor: visual
page-layout: full
